CREATE TABLE "addresses" (
  "address_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "street_address" varchar,
  "city" varchar,
  "state" varchar,
  "zip_code" varchar,
  "latitude" decimal,
  "longitude" decimal
);

CREATE TABLE "households" (
  "household_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "household_name" varchar,
  "address_id" int
);

CREATE TABLE "citizens" (
  "citizen_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "date_of_birth" date,
  "email" varchar,
  "phone" varchar,
  "household_id" int
);

CREATE TABLE "city_services" (
  "service_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_name" varchar,
  "description" varchar
);

CREATE TABLE "service_requests" (
  "request_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "citizen_id" int,
  "service_id" int,
  "description" varchar,
  "status" varchar,
  "request_date" timestamp,
  "resolution_date" timestamp
);

CREATE TABLE "venues" (
  "venue_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "address_id" int,
  "capacity" int
);

CREATE TABLE "community_events" (
  "event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_name" varchar,
  "description" varchar,
  "event_date" timestamp,
  "venue_id" int
);

CREATE TABLE "citizen_feedback" (
  "feedback_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "citizen_id" int,
  "service_id" int,
  "subject" varchar,
  "description" varchar,
  "rating" int,
  "feedback_date" timestamp
);

CREATE TABLE "citizen_clubs" (
  "club_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar
);

CREATE TABLE "citizen_club_members" (
  "club_id" int,
  "citizen_id" int,
  "join_date" date,
  PRIMARY KEY ("club_id", "citizen_id")
);

ALTER TABLE "households" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("address_id");

ALTER TABLE "citizens" ADD FOREIGN KEY ("household_id") REFERENCES "households" ("household_id");

ALTER TABLE "service_requests" ADD FOREIGN KEY ("citizen_id") REFERENCES "citizens" ("citizen_id");

ALTER TABLE "service_requests" ADD FOREIGN KEY ("service_id") REFERENCES "city_services" ("service_id");

ALTER TABLE "venues" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("address_id");

ALTER TABLE "community_events" ADD FOREIGN KEY ("venue_id") REFERENCES "venues" ("venue_id");

ALTER TABLE "citizen_feedback" ADD FOREIGN KEY ("citizen_id") REFERENCES "citizens" ("citizen_id");

ALTER TABLE "citizen_feedback" ADD FOREIGN KEY ("service_id") REFERENCES "city_services" ("service_id");

ALTER TABLE "citizen_club_members" ADD FOREIGN KEY ("club_id") REFERENCES "citizen_clubs" ("club_id");

ALTER TABLE "citizen_club_members" ADD FOREIGN KEY ("citizen_id") REFERENCES "citizens" ("citizen_id");
